PERGUNTAS_PORTAGE = {
    "Socialização": {
        1: [
            "Observa uma pessoa movimentando-se em seu campo visual.",
            "Sorri em resposta à atenção do adulto.",
            "Vocaliza em resposta à atenção.",
            "Olha para sua própria mão, sorrindo ou vocalizando.",
            "Responde a seu círculo familiar, sorrindo, vocalizando ou parando de chorar.",
            "Sorri em resposta à expressão facial dos outros.",
            "Sorri e vocaliza ao ver sua imagem no espelho.",
            "Acaricia ou toca no rosto de adultos (puxa cabelo, nariz, óculos, etc.).",
            "Estende a mão em direção a um objeto oferecido.",
            "Estende os braços em direção a pessoas familiares.",
            "Estende a mão e toca sua imagem refletida no espelho.",
            "Segura e examina por 1 minuto um objeto que lhe foi dado.",
            "Sacode ou aperta um objeto colocado em sua mão, produzindo sons involuntários.",
            "Brinca sozinho por 10 minutos.",
            "Procura contato visual quando alguém lhe dá atenção por 2 a 3 minutos.",
            "Brinca sozinho sem reclamar por 15 a 20 minutos, próximo de um adulto.",
            "Vocaliza para obter atenção.",
            "Imita adulto em brincadeiras de esconde-esconde.",
            "Bate palmas, imitando um adulto.",
            "Acena a mão, imitando um adulto.",
            "Ergue os braços para expressar \"grande\", imitando um adulto.",
            "Oferece algo, mas nem sempre entrega.",
            "Abraça, acaricia e beija familiares.",
            "Responde ao próprio nome, olhando ou estendendo o braço para ser pego.",
            "Aperta ou sacode um brinquedo para produzir sons, em imitação.",
            "Manipula brinquedo ou objeto.",
            "Estende um brinquedo ou objeto a um adulto e o entrega.",
            "Imita movimentos de outras crianças ao brincar."
        ],
        2: [
            "Imita um adulto em uma tarefa simples.",
            "Brinca ao lado de outra criança, cada uma realizando tarefas diferentes.",
            "Toma parte em uma brincadeira com outra criança por 2 a 5 minutos.",
            "Aceita a ausência dos pais, embora possa reclamar.",
            "Explora ativamente seu meio ambiente.",
            "Realiza atividade manipulativa com outra pessoa.",
            "Abraça e carrega uma boneca ou brinquedo macio.",
            "Repete ações que produzem risos e atenção.",
            "Dá um livro para que um adulto o leia ou para que ambos o compartilhem.",
            "Puxa uma pessoa a mostrar-lhe algo.",
            "Retira a mão ou diz 'não' quando está próximo de um objeto não permitido e alguém o lembra disto.",
            "Quando colocado em sua cadeira ou trocador espera ser atendido.",
            "Brinca com 2 ou 3 crianças da sua idade.",
            "Compartilha um objeto ou alimento com outra criança.",
            "Cumprimenta colegas ou adultos quando lembrado."
        ],
        3: [
            "Obedece às ordens dos pais pelo menos 1/2 das vezes.",
            "Busca / leva um objeto ou pessoa, quando solicitado.",
            "Presta atenção à estória ou música por 5 a 10 min.",
            "Diz 'Por favor' ou 'Obrigado' quando lembrado.",
            "Tenta ajudar os pais a executarem tarefas realizando parte da mesma.",
            "Brinca de usar roupas de adultos.",
            "Faz uma escolha quando indagado.",
            "Demonstra entender sentimentos, expressando-os."
        ],
        4: [
            "Canta e dança ao ouvir músicas.",
            "Segue regras de um jogo imitando ações de outras crianças.",
            "Cumprimenta pessoas familiares sem ser lembrado.",
            "Seguem regras em jogos de grupos dirigidos por adultos.",
            "Pede permissão para brincar com um brinquedo que está sendo usado por outra criança.",
            "Diz 'Por favor' e 'Obrigado' sem ser lembrado 1/2 das vezes.",
            "Atende ao telefone, chamando um adulto e falando com pessoas familiares.",
            "Espera a sua vez.",
            "Segue regras em jogos dirigidos por uma criança mais velha.",
            "Obedece às ordens de um adulto 75% das vezes (3 vezes a cada 4 tentativas).",
            "Permanece em seu próprio quintal ou jardim.",
            "Brinca perto de outras crianças conversando com elas enquanto trabalha em um projeto próprio (30 min.)."
        ],
        5: [
            "Pede ajuda quando está tendo dificuldades.",
            "Contribui para a conversa de adultos.",
            "Repete rimas, canções ou dança para os outros.",
            "Faz uma tarefa sozinha por 20 a 30 minutos.",
            "Pede desculpas sem ser lembrado 75% das vezes.",
            "Espera sua vez em brincadeiras que envolvam de 8 a 9 crianças.",
            "Brinca com 2 a 3 crianças por 20 min. em uma atividade que envolva cooperação.",
            "Quando em público, apresenta um comportamento socialmente aceitável.",
            "Pede permissão para usar objetos dos outros em 75% das vezes."
        ],
        6: [
            "Manifesta seus sentimentos.",
            "Brinca com 4 a 5 crianças em atividade de cooperação por 20 minutos, sem supervisão.",
            "Explica aos outros as regras do jogo ou atividade.",
            "Imita papéis de adulto.",
            "Colabora para a conversa durante as refeições.",
            "Segue regras de jogo que envolva raciocínio verbal.",
            "Conforta colegas quando estes estão tristes.",
            "Escolhe seus próprios amigos.",
            "Planeja e constrói, usando ferramentas simples.",
            "Estabelece metas para si próprio e executa atividade para atingi-las.",
            "Dramatiza trechos de histórias, desempenhando um papel ou utilizando fantoches."
        ]
    },
    "Linguagem": {
        1: [
            "Repete sons emitidos por outras pessoas.",
            "Repete a mesma sílaba 2 a 3 vezes.",
            "Responde a gestos com gestos.",
            "Obedece a uma ordem simples, quando acompanhada de gestos indicativos.",
            "Interrompe a atividade quando lhe dizem 'Não' 75% das vezes.",
            "Responde a perguntas simples com respostas não verbais.",
            "Combina 2 sílabas diferentes quando tenta verbalizar.",
            "Imita padrões de entonação da voz de outras pessoas.",
            "Usa uma palavra funcionalmente para indicar objetos ou pessoas.",
            "Vocaliza em resposta à fala de outras pessoas."
        ],
        2: [
            "Diz 5 palavras diferentes.",
            "Pede 'mais'.",
            "Diz 'acabou'.",
            "Obedece a 3 ordens diferentes que não são acompanhadas de gestos indicativos.",
            "Consegue 'dar' ou 'mostrar' quando solicitado.",
            "Aponta para 12 objetos quando nomeados.",
            "Aponta para 3 a 5 figuras em um livro.",
            "Aponta para 3 partes de seu próprio corpo.",
            "Diz seu nome ou apelido quando solicitado.",
            "Responde à pergunta 'O que é isto?'.",
            "Combina palavras e gestos para expressar desejos.",
            "Nomeia 5 membros da família, incluindo animais.",
            "Nomeia 4 brinquedos.",
            "Produz sons de animais, ou os nomeia pelo som.",
            "Pede alimentos conhecidos pelo nome, quando mostrados.",
            "Faz perguntas variando a entonação da voz.",
            "Nomeia 3 partes do corpo em uma boneca ou outra pessoa.",
            "Responde a perguntas de sim / não."
        ],
        3: [
            "Combina substantivos ou adjetivos e substantivos em frases de 2 palavras.",
            "Combina substantivo e verbo em frases de 2 palavras.",
            "Usa uma palavra para indicar que quer ir ao banheiro.",
            "Combina verbo ou substantivo com 'lá' e 'aqui' em frases de 2 palavras.",
            "Combina 2 palavras para expressar posse.",
            "Emprega 'não' na fala.",
            "Responde à pergunta 'O que ... está fazendo?' para atividades habituais.",
            "Responde a perguntas tipo 'Onde está o objeto?'.",
            "Nomeia sons ambientais familiares.",
            "Dá mais de um objeto quando se usa a forma plural na solicitação.",
            "Ao falar, refere-se a si próprio pelo nome.",
            "Aponta para figuras de objetos comuns descritos pelo uso.",
            "Mostra a idade pelos dedos.",
            "Diz seu sexo quando solicitado.",
            "Obedece à sequência de duas ordens relacionadas.",
            "Usa a forma do verbo no gerúndio.",
            "Emprega formas regulares no plural.",
            "Emprega algumas formas irregulares de verbos no passado de forma sistemática.",
            "Faz perguntas do tipo 'O que é isso?'.",
            "Controla o volume da voz 90% das vezes.",
            "Usa 'este / esta' e 'aquele / aquela' na fala.",
            "Emprega 'e' e 'está' em frases simples.",
            "Diz 'eu', 'mim', 'meu' ao invés do próprio nome.",
            "Aponta objetos e diz que eles não são outras coisas.",
            "Responde à pergunta 'Quem?' dando um nome.",
            "Emprega as formas possessivas dos substantivos.",
            "Usa artigos ao falar.",
            "Usa substantivos que indicam grupo ou categoria.",
            "Usa os verbos 'ser', 'estar' e 'ter' no presente com poucos erros.",
            "Diz se os objetos estão abertos ou fechados."
        ],
        4: [
            "Expressa diminutivos e aumentativos quando fala.",
            "Presta atenção por 5 minutos a uma história lida.",
            "Obedece à sequência de 2 ordens não relacionadas.",
            "Diz seu nome completo quando solicitado.",
            "Responde perguntas simples envolvendo 'Como'.",
            "Emprega verbos regulares no passado.",
            "Relata experiências imediatas.",
            "Diz como são usados objetos comuns.",
            "Expressa ações futuras empregando os verbos 'ir', 'ter' e 'querer'.",
            "Utiliza adequadamente masculino e feminino na fala.",
            "Usa formas imperativas de verbos ao pedir favores.",
            "Conta 2 fatos na ordem de ocorrência."
        ],
        5: [
            "Obedece a uma sequência envolvendo 3 ordens.",
            "Demonstra compreensão de verbos reflexivos, usando-os ocasionalmente.",
            "Consegue identificar objetos ou figuras que formem par, sob solicitação.",
            "Emprega o futuro ao falar.",
            "Usa orações compostas por coordenação.",
            "Consegue identificar a parte de cima e de baixo de objetos, quando solicitado.",
            "Emprega ocasionalmente o condicional ao falar (poderia, pudesse, iria, seria, faria).",
            "Consegue identificar absurdos em figuras.",
            "Emprega palavras como irmã(o), avó, avô.",
            "Completa frases com antônimos.",
            "Relata uma história conhecida sem ajuda de figuras.",
            "Em uma figura, nomeia o objeto que não pertence a uma determinada categoria.",
            "Diz se duas palavras rimam ou não.",
            "Usa frases complexas, compostas por subordinação.",
            "Diz se um som é forte ou fraco."
        ],
        6: [
            "Consegue indicar alguns, muitos e vários elementos.",
            "Diz seu endereço.",
            "Diz o número de seu telefone.",
            "Aponta para o conjunto que tem mais, menos ou poucos elementos.",
            "Conta piadas simples.",
            "Relata experiências diárias.",
            "Descreve um local ou movimento: através ou entre, longe de, de / desde..., para, por cima de, até.",
            "Responde à pergunta 'Por quê?' com uma explicação.",
            "Ordena e conta uma história de 2 a 5 episódios na sequência correta.",
            "Define palavras.",
            "Responde adequadamente à pergunta 'Qual o contrário de ...?'.",
            "Responde à pergunta 'O que acontece se...?'.",
            "Usa 'ontem' e 'amanhã' corretamente.",
            "Pergunta o significado de perguntas novas ou conhecidas."
        ]
    },
    "Cognição": {
        1: [
            "Remove um pano do rosto que obscureça sua visão.",
            "Procura com o olhar um objeto que foi tirado de seu campo visual.",
            "Remove um objeto de um recipiente colocando a mão dentro do mesmo.",
            "Coloca um objeto em um recipiente imitando um adulto.",
            "Coloca um objeto em um recipiente quando recebe instruções.",
            "Balança um brinquedo que produz som, pendurado em um barbante.",
            "Coloca três objetos em um recipiente e o esvazia.",
            "Transfere um objeto de uma mão à outra para apanhar outro objeto.",
            "Deixa cair e apanha um brinquedo.",
            "Descobre um objeto escondido sob um recipiente.",
            "Empurra 3 blocos como se fosse um comboio.",
            "Remove um círculo de uma prancha, por imitação.",
            "Coloca um pino redondo em uma prancha de pinos, quando solicitado.",
            "Executa gestos simples quando requisitado."
        ],
        2: [
            "Retira 6 objetos de um recipiente, um por vez.",
            "Aponta para uma parte do corpo.",
            "Empilha 3 blocos, dada a ordem.",
            "Emparelha objetos semelhantes.",
            "Faz rabiscos no papel.",
            "Aponta para si quando perguntam 'Cadê o Fulano?'.",
            "Coloca 5 pinos redondos, dada a ordem.",
            "Emparelha objetos com a figura do mesmo nome.",
            "Aponta para a figura nomeada.",
            "Vira as páginas de um livro (2/3 por vez) para encontrar a figura nomeada."
        ],
        3: [
            "Encontra determinado livro quando solicitado.",
            "Completa um quebra-cabeça de encaixe de 3 peças.",
            "Nomeia 4 objetos comuns em figuras.",
            "Desenha uma linha vertical imitando um adulto.",
            "Desenha uma linha horizontal imitando um adulto.",
            "Copia um círculo.",
            "Emparelha objetos com a mesma textura.",
            "Aponta o 'pequeno' e o 'grande' quando solicitado.",
            "Desenha (+) imitando um adulto.",
            "Emparelha 3 cores.",
            "Coloca objetos dentro, em cima e embaixo de um recipiente, dada a ordem.",
            "Nomeia objetos quando ouve o barulho que fazem.",
            "Monta um brinquedo de encaixe de 4 peças.",
            "Nomeia ações em figuras ('O que ... está fazendo?').",
            "Emparelha forma geométrica com a figura da mesma.",
            "Empilha 5 ou mais argolas em uma vara na ordem."
        ],
        4: [
            "Nomeia objetos como sendo grandes ou pequenos.",
            "Aponta para 10 partes do corpo quando requisitado.",
            "Aponta para menino e menina, dada a ordem.",
            "Diz se um objeto é pesado ou leve.",
            "Une 2 partes de uma figura para formar o todo.",
            "Descreve 2 eventos ou personagens de uma história familiar ou programa de televisão.",
            "Repete brincadeiras (rimas ou canções) que envolvam movimentos coordenados.",
            "Emparelha 3 ou mais objetos.",
            "Aponta para objetos compridos ou curtos.",
            "Associa objetos correspondentes (ex: meia/sapato).",
            "Conta até 3 imitando um adulto.",
            "Agrupa objetos em categorias.",
            "Traça um (V) em imitação.",
            "Traça uma linha diagonal dado o exemplo.",
            "Conta até 10 objetos, imitando um adulto.",
            "Constrói uma ponte com 3 blocos por imitação.",
            "Emparelha uma sequência ou padrão (tamanho, cor) de blocos ou contas.",
            "Copia uma série de (V) interligados.",
            "Acrescenta perna ou braço em um desenho incompleto da figura humana.",
            "Completa um quebra-cabeças de 6 peças.",
            "Indica se os objetos são iguais ou diferentes.",
            "Desenha um quadrado imitando um adulto.",
            "Nomeia 3 cores sendo requisitado.",
            "Nomeia 3 formas geométricas (quadrado, triângulo e círculo)."
        ],
        5: [
            "Apanha de 1 a 5 objetos quando solicitado.",
            "Nomeia 5 texturas diferentes.",
            "Copia um triângulo ao ser requisitado.",
            "Recorda-se de 4 objetos que haviam sido vistos em uma figura.",
            "Diz o momento do dia associado a cada atividade.",
            "Repete rimas familiares.",
            "Diz se um objeto é mais pesado ou mais leve (objetos com diferença de 0,5 quilo).",
            "Diz o que está faltando quando um objeto é retirado de um grupo de 3 objetos.",
            "Nomeia 8 cores.",
            "Identifica o valor de 3 moedas.",
            "Emparelha símbolos (letras e números).",
            "Diz a cor de objetos nomeados.",
            "Relata 5 principais fatos de uma história contada 3x.",
            "Desenha figura humana (cabeça, tronco e 4 membros).",
            "Canta 5 estrofes de uma canção.",
            "Constrói uma pirâmide de 10 blocos por imitação.",
            "Nomeia objetos como sendo compridos ou curtos.",
            "Coloca objetos 'atrás', 'ao lado' ou 'junto' a outros.",
            "Faz conjuntos iguais de 10 objetos, segundo modelo.",
            "Nomeia ou aponta para a parte ausente da figura.",
            "Conta de 1 a 20.",
            "Identifica o objeto que está colocado no meio, em primeiro e em último lugar."
        ],
        6: [
            "Conta até 20 objetos e responde adequadamente à pergunta: 'Quantos ... você contou?'.",
            "Nomeia 10 numerais.",
            "Identifica qual a sua esquerda e qual a sua direita.",
            "Diz as vogais em ordem.",
            "Escreve seu nome com letras de forma.",
            "Nomeia 5 letras do alfabeto.",
            "Ordena objetos em sequência de comprimento e largura.",
            "Nomeia as letras maiúsculas do alfabeto.",
            "Coloca numerais de 1 a 10 na sequência correta.",
            "Identifica a posição de objetos em 1º, 2º e 3º lugar.",
            "Nomeia as letras minúsculas do alfabeto.",
            "Emparelha letras maiúsculas com minúsculas.",
            "Aponta para numerais de 1 a 25.",
            "Copia um losango.",
            "Completa um labirinto simples.",
            "Diz os dias da semana na ordem.",
            "Soma e subtrai combinações de até 3 elementos.",
            "Diz o mês e o dia de seu aniversário.",
            "Lê 10 palavras impressas.",
            "Prediz o que vai ocorrer.",
            "Aponta para objetos inteiros e partidos ao meio.",
            "Conta de memória de 1 a 100 (pedir que pare no 40, e continue no 80, caso não erre até o 40)."
        ]
    },
    "Auto cuidado": {
        1: [
            "Suga e deglute líquidos.",
            "Toma mingau / sopinha.",
            "Estende as mãos em direção à mamadeira, tentando pegá-la.",
            "Come alimentos liquidificados dados pelos pais.",
            "Segura a mamadeira sem ajuda enquanto bebe.",
            "Leva a mamadeira até a boca ou a recusa, empurrando-a.",
            "Come alimentos amassados dados pelos pais.",
            "Bebe em uma caneca, segurada pelos pais.",
            "Come alimentos semissólidos dados pelos pais.",
            "Alimenta-se sozinho usando os dedos.",
            "Segura a caneca com ambas as mãos e bebe.",
            "Leva a colher cheia de comida até a boca com ajuda.",
            "Estica braços e pernas ao ser vestido."
        ],
        2: [
            "Come com colher de modo independente.",
            "Segura a caneca com uma só mão e bebe.",
            "Coloca a mão na água e dá tapinhas no rosto com as mãos molhadas, imitando alguém.",
            "Senta-se em um piniquinho ou sanitário infantil por 5 min.",
            "Coloca um chapéu na cabeça e o remove.",
            "Tira as meias.",
            "Empurra os braços pelas mangas e os pés pelas pernas da calça.",
            "Tira os sapatos quando os cordões estiverem desamarrados.",
            "Tira o casaco quando desabotoado.",
            "Tira a calça quando desabotoada.",
            "Puxa um fecho grande para cima e para baixo.",
            "Utiliza palavras ou gestos indicando necessidade de ir ao banheiro."
        ],
        3: [
            "Alimenta-se sozinho usando colher ou caneca, derrubando um pouco de comida ou derramando pouco líquido.",
            "Quando recebe uma toalha enxuga as mãos e o rosto com ajuda.",
            "Suga líquido do copo ou caneca usando canudinho.",
            "Dá garfadas.",
            "Mastiga e engole apenas substâncias comestíveis.",
            "Enxuga as mãos sem ajuda ao lhe darem uma toalha.",
            "Avisa que quer ir ao banheiro, mesmo sendo tarde demais.",
            "Controla sua baba.",
            "Urina ou defeca quando colocado no piniquinho pelo menos 3 vezes por semana.",
            "Calça os sapatos.",
            "Escova os dentes imitando um adulto.",
            "Retira roupas simples que foram desabotoadas.",
            "Usa o banheiro para defecar (falha apenas 1x por semana).",
            "Obtém água de uma torneira sem ajuda.",
            "Lava as mãos e o rosto com um sabonete.",
            "Avisa que quer ir ao banheiro durante o dia a tempo.",
            "Pendura o casaco em um gancho da sua altura.",
            "Permanece seco ao dormir durante o dia.",
            "Evita riscos, por ex: pontas em móveis e escadas sem corrimão.",
            "Usa guardanapo quando recomendado.",
            "Espeta o garfo na comida, levando-a à boca.",
            "Despeja líquido de uma pequena jarra para o copo sem ajuda.",
            "Desprende roupas presas com o feixe de pressão.",
            "Lava seus braços e pernas ao lhe darem banho.",
            "Coloca meias.",
            "Veste casaco, malha ou camisa.",
            "Identifica a parte dianteira da roupa."
        ],
        4: [
            "Alimenta-se sozinho por toda a refeição.",
            "Veste-se só, precisando de ajuda apenas quanto há malhas ou camisetas com golas fechadas ou botões e fechos.",
            "Enxuga o nariz quando lembrado.",
            "Acorda seco 2 manhãs por semana.",
            "Se menino, urina no sanitário, em pé.",
            "Veste-se e despe-se sozinho, exceto quanto à botões e fechos em 75% das vezes.",
            "Fecha a roupa com fechos de pressão ou de gancho.",
            "Assoa o nariz quando lembrado.",
            "Evita perigos corriqueiros, por ex: caco de vidro.",
            "Pendura roupa no cabide e põe no armário quando pedem.",
            "Escova os dentes quando recebe instrução.",
            "Coloca luvas.",
            "Desabotoa botões grandes.",
            "Abotoa botões grandes.",
            "Calça botas."
        ],
        5: [
            "Limpa o que derramou por conta própria.",
            "Evita veneno e todas as substâncias prejudiciais.",
            "Desabotoa sua roupa.",
            "Abotoa sua roupa.",
            "Retira prato e talheres da mesa.",
            "Encaixa fecho em sua terminação.",
            "Lava as mãos e o rosto.",
            "Usa talher apropriado para alimentar-se.",
            "Acorda de noite para ir ao banheiro, ou acorda seco.",
            "Limpa e assua o nariz em 75% das vezes sem ser lembrado.",
            "Toma banho só, precisando de ajuda apenas para lavar as costas, pescoço e orelhas.",
            "Usa faca para espalhar manteiga no pão.",
            "Aperta e afrouxa cintos ou fivelas.",
            "Veste-se sozinho, mas não dá laços.",
            "Serve-se à mesa enquanto seguram a travessa de comida.",
            "Ajuda a pôr a mesa corretamente quando recebe instruções.",
            "Escova os dentes.",
            "Vai ao banheiro a tempo, retira a roupa, usa papel higiênico, dá descarga e veste-se sem ajuda.",
            "Penteia ou escova cabelos.",
            "Pendura roupas em cabides.",
            "Anda pela vizinhança sem constante supervisão.",
            "Enfia cordões em sapatos.",
            "Amarra ou dá laços nos cordões dos sapatos."
        ],
        6: [
            "É responsável por uma tarefa semanal e a executa ao ser lembrado.",
            "Seleciona roupas apropriadas ao clima e ocasião.",
            "Pára no passeio, olha para ambos os lados, e atravessa a rua sem precisar ser lembrado.",
            "Serve-se à mesa e passa aos demais a panela de comida.",
            "Prepara sua própria caneca de café com leite.",
            "É responsável por uma tarefa diária em casa.",
            "Ajusta a temperatura da água para o banho.",
            "Prepara seu próprio lanche.",
            "Anda sozinho até a distância de 2 quadras de casa.",
            "Corta alimentos tenros com faca.",
            "Encontra o banheiro em local público, corretamente.",
            "Abre a embalagem de leite.",
            "Apanha uma bandeja com comida, levando-a e pondo sobre a mesa.",
            "Amarra os cordões em casacos com capuz.",
            "Aperta o cinto de segurança do automóvel."
        ]
    },
    "Desenvolvimento Motor": {
        1: [
            "Alcança um objeto colocado à sua frente (15 a 20 cm.).",
            "Apanha um objeto colocado à sua frente (8 cm.).",
            "Estende os braços em direção a um objeto à sua frente e o apanha.",
            "Alcança um objeto preferido.",
            "Coloca objetos na boca.",
            "Eleva a cabeça e o tronco apoiando-se nos braços, ao estar deitado de barriga para baixo.",
            "Levanta a cabeça e o tronco apoiando-se em um só braço.",
            "Toca e explora objetos com a boca.",
            "Em DV (decúbito ventral), vira de lado e mantém esta posição 1/2 das vezes.",
            "Em DV, vira de costas.",
            "Em DV, move-se para frente o equivalente à sua altura.",
            "Em DD (decúbito dorsal), rola para o lado.",
            "Em DD, vira de barriga para baixo.",
            "Faz esforço para sentar-se, segurando nos dedos do adulto.",
            "Vira a cabeça com facilidade quando o corpo está apoiado.",
            "Mantém-se sentado por 2 minutos.",
            "Solta um objeto para apanhar outro.",
            "Apanha e deixa cair um objeto propositalmente.",
            "Fica em pé com o máximo de apoio.",
            "Estando em pé com apoio, pula para cima e para baixo.",
            "Engatinha para apanhar um objeto (distante a sua altura).",
            "Senta-se apoiando-se sozinho.",
            "Estando sentado, vira de gatinhas.",
            "Estando em DV consegue sentar-se.",
            "Senta-se sem o apoio das mãos.",
            "Atira objetos ao acaso.",
            "Balança para frente e para trás quando de gatinhas.",
            "Transfere objetos de uma mão para outra quando sentado.",
            "Retém em uma das mãos 2 cubos de 2,5 cm.",
            "Fica de joelhos.",
            "Fica em pé, apoiando-se em algo.",
            "Usa preensão de pinça para pegar objetos.",
            "Engatinha.",
            "Estando de gatinhas, estende uma das mãos para o alto.",
            "Fica em pé com o mínimo de apoio.",
            "Lambe a comida ao redor da boca.",
            "Mantém-se em pé sozinho por um minuto.",
            "Derruba um objeto que está dentro de um recipiente.",
            "Vira várias páginas de um livro ao mesmo tempo.",
            "Escava com uma colher ou pá.",
            "Coloca pequenos objetos dentro do recipiente.",
            "Estando de pé, abaixa-se e senta.",
            "Bate palmas.",
            "Anda com um mínimo de apoio.",
            "Dá alguns passos sem apoio."
        ],
        2: [
            "Sobe escadas engatinhando.",
            "Coloca-se em pé, estando sentado.",
            "Rola uma bola imitando um adulto.",
            "Sobe em uma cadeira de adulto, vira-se e senta.",
            "Coloca 4 aros em uma pequena estaca.",
            "Retira pinos de 2,5 cm de uma prancha ou tabuleiro.",
            "Encaixa pinos de 2,5 cm em uma prancha de encaixe.",
            "Constrói uma torre de 3 blocos.",
            "Faz traços no papel com lápis ou lápis de cera.",
            "Anda sozinho.",
            "Desce escadas sentado, colocando primeiro os pés.",
            "Senta-se em uma cadeirinha.",
            "Agacha-se e volta a ficar em pé.",
            "Empurra e puxa brinquedos ao andar.",
            "Usa cadeira ou cavalo de balanço.",
            "Sobe escadas com ajuda.",
            "Dobra o corpo sem cair para apanhar objetos no chão.",
            "Imita um movimento circular."
        ],
        3: [
            "Enfia 4 contas grandes em um cordão em 2 minutos.",
            "Vira trincos ou maçanetas em portas.",
            "Salta no mesmo local com ambos os pés.",
            "Anda de costas.",
            "Desce escadas sem ajuda.",
            "Atira uma bola a um adulto à 1 1/2 de distância.",
            "Constrói uma torre de 5 a 6 blocos.",
            "Vira páginas de um livro, uma por vez.",
            "Desembrulha um pequeno objeto.",
            "Dobra um papel ao meio, imitando um adulto.",
            "Desmancha e reconstrói brinquedos de encaixe por pressão.",
            "Desenrosca brinquedos que se encaixam por roscas.",
            "Chuta uma bola grande que está imóvel.",
            "Faz bolas de argila, barro ou massinha.",
            "Segura o lápis entre o polegar e o indicador, apoiando-o sobre o dedo médio.",
            "Dá cambalhota para frente com ajuda.",
            "Dá marteladas para encaixar 5 pinos em seus orifícios."
        ],
        4: [
            "Faz um quebra cabeça de 3 peças.",
            "Corta algo em pedaços com tesoura.",
            "Pula de uma altura de 20 cm.",
            "Chuta uma bola grande quando enviada para si.",
            "Anda na ponta dos pés.",
            "Corre 10 passos coordenando e alternando o movimento dos braços e pés.",
            "Pedala com triciclo a distância de 1 metro e 1/2.",
            "Balança em um balanço quando este está em movimento.",
            "Sobe em um escorregador de 1,20m a 1,80m e escorrega.",
            "Dá cambalhotas para frente.",
            "Sobe escadas alternando os pés.",
            "Marcha (anda de forma ritmada).",
            "Apara a bola com ambas as mãos.",
            "Desenha figuras seguindo contornos ou pontilhados.",
            "Recorta ao longo de uma linha reta 20 cm, afastando-se pouco da linha."
        ],
        5: [
            "Fica em um só pé sem apoio por 4 a 8 segundos.",
            "Muda de direção ao correr.",
            "Anda sobre uma viga ou tábua, mantendo o equilíbrio.",
            "Pula para frente 10 vezes sem cair.",
            "Salta sobre uma corda suspensa a 5 cm do solo.",
            "Pula de costas 6 vezes.",
            "Rebate e apanha uma bola grande.",
            "Une 2 a 3 pedaços de massa de modelar.",
            "Recorta em torno de linhas curvas.",
            "Encaixa objetos de rosca.",
            "Desce escadas alternando os pés.",
            "Pedala um triciclo fazendo curvas.",
            "Salta em um só pé 5 vezes consecutivas.",
            "Recorta um círculo em 5 cm.",
            "Desenha figuras simples facilmente identificáveis (por ex: casa).",
            "Recorta e cola formas simples."
        ],
        6: [
            "Escreve letras de imprensa maiúsculas, isoladas e grandes em qualquer lugar do papel.",
            "Anda sobre uma tábua para trás, para frente e para os lados, mantendo o equilíbrio.",
            "Caminha saltitando.",
            "Balança em um balanço iniciando e mantendo o movimento.",
            "Estica os dedos tocando o polegar em cada um deles.",
            "Copia letras maiúsculas.",
            "Sobe em escadas de mão ou de escorregador de 3 m.",
            "Bate em um prego com martelo.",
            "Rebate a bola à medida que anda com direção.",
            "Consegue colorir sem sair da margem em 95% das vezes.",
            "Recorta figuras sem sair mais que 6 mm da margem.",
            "Usa apontador de lápis.",
            "Copia desenhos complexos (escola, navio).",
            "Rasga figuras simples de um papel.",
            "Dobra um papel quadrado 2x em diagonal por imitação.",
            "Apanha uma bola leve com uma só mão.",
            "Pula corda sozinho.",
            "Golpeia uma bola com um bastão ou pedaço de pau.",
            "Apanha um objeto no chão enquanto corre.",
            "Patina uma distância de 3 m, ou usa skate.",
            "Anda de bicicleta.",
            "Escorrega descendo um monte de areia ou terra.",
            "Anda ou brinca em piscina tendo água até a cintura.",
            "Conduz um patinete dando impulso com um só pé.",
            "Salta e gira em um só pé.",
            "Escreve seu nome com letras de forma em caderno pautado.",
            "Salta de uma altura de 30 cm e cai na ponta dos pés.",
            "Pára em um só pé sem apoio com olhos fechados por 10 segundos.",
            "Dependura-se por 10 segundos em uma barra horizontal."
        ]
    }
}
